/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx}",
    "./lib/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "outline-variant": "#424754",
        "on-error-container": "#ffdad6",
        "tertiary": "#ffb3ad",
        "surface-container": "#201f1f",
        "secondary-container": "#00b954",
        "primary-fixed-dim": "#adc6ff",
        "surface": "#131313",
        "primary-fixed": "#d8e2ff",
        "surface-tint": "#adc6ff",
        "on-primary-fixed": "#001a42",
        "surface-container-lowest": "#0e0e0e",
        "surface-variant": "#353534",
        "on-secondary-container": "#004119",
        "on-error": "#690005",
        "surface-container-high": "#2a2a2a",
        "on-tertiary-fixed-variant": "#930013",
        "tertiary-container": "#ff5451",
        "inverse-on-surface": "#313030",
        "surface-container-highest": "#353534",
        "on-background": "#e5e2e1",
        "on-tertiary": "#68000a",
        "on-secondary-fixed": "#002109",
        "inverse-surface": "#e5e2e1",
        "on-tertiary-fixed": "#410004",
        "on-secondary-fixed-variant": "#005321",
        "surface-bright": "#3a3939",
        "tertiary-fixed-dim": "#ffb3ad",
        "secondary": "#4ae176",
        "surface-container-low": "#1c1b1b",
        "tertiary-fixed": "#ffdad7",
        "on-primary-container": "#00285d",
        "outline": "#8c909f",
        "on-secondary": "#003915",
        "background": "#131313",
        "primary": "#adc6ff",
        "inverse-primary": "#005ac2",
        "on-primary": "#002e6a",
        "on-tertiary-container": "#5c0008",
        "on-primary-fixed-variant": "#004395",
        "on-surface-variant": "#c2c6d6",
        "error-container": "#93000a",
        "secondary-fixed-dim": "#4ae176",
        "surface-dim": "#131313",
        "secondary-fixed": "#6bff8f",
        "error": "#ffb4ab",
        "on-surface": "#e5e2e1",
        "primary-container": "#4d8eff",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Space Grotesk", "monospace"],
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
  ],
};
